name = "immigrationapi"
main = "src/index.ts"
compatibility_date = "2024-10-23"
compatibility_flags = [ "nodejs_compat" ]
[env.dev]
  NODE_ENV = "development"  # Set NODE_ENV to development

[env.production]
  NODE_ENV = "production"

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_ZW1lcmdpbmctd2FydGhvZy0yNC5jbGVyay5hY2NvdW50cy5kZXYk"
CLERK_PUBLISHABLE_KEY="pk_test_ZW1lcmdpbmctd2FydGhvZy0yNC5jbGVyay5hY2NvdW50cy5kZXYk"
CLERK_SECRET_KEY="sk_test_f6z0wLBN8XOBJOf07h9a951IU0sccOrXSGLWjoJLUX"
CLERK_WEBHOOK_SECRET="sk_test_f6z0wLBN8XOBJOf07h9a951IU0sccOrXSGLWjoJLUX"


[[kv_namespaces]]
binding = "immigration-app"
id = "0f7428ded27f46fbb862bff1b6673a9c"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "immigration-app-db"
database_id = "03d52fa4-bcbd-4a44-ac71-05b1582a8411"
migrations_dir = "drizzle/migrations"